[package]
name = "rti-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "rti-db TCP line protocol server (put/scan)"

[dependencies]
rti-core = { path = "../rti-core" , version = "0.8.0" }
rti-query = { path = "../rti-query" , version = "0.8.0" }
rti-db = { path = "../rti-db" , version = "0.8.0" }
