#ifndef RTI_VLA_H
#define RTI_VLA_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success: operation completed, no sample produced (end of stream / empty series).
 */
#define RTI_OK 0

/**
 * Success: a sample was produced (written to the out-parameter).
 */
#define RTI_SAMPLE 1

/**
 * Error: a required pointer argument was null.
 */
#define RTI_ERR_NULL -1

/**
 * Error: chunk buffer full (backpressure; seal the chunk, then retry).
 */
#define RTI_ERR_FULL -2

/**
 * Error: invalid argument (e.g. degenerate window span, zero series length).
 */
#define RTI_ERR_INVALID -3

/**
 * Error: internal engine error.
 */
#define RTI_ERR_INTERNAL -4

/**
 * Opaque chunk-buffer handle.
 */
typedef struct RtiChunk RtiChunk;

/**
 * Opaque database handle (owns one `Arc<Db>` refcount).
 */
typedef struct RtiDb RtiDb;

/**
 * Opaque window iterator handle.
 */
typedef struct RtiWindow RtiWindow;

/**
 * C-facing sample layout (`#[repr(C)]`, 16 bytes: nanosecond ts + f64 value).
 */
typedef struct RtiSample {
  /**
   * Nanosecond timestamp.
   */
  int64_t ts;
  /**
   * Sample value.
   */
  double value;
} RtiSample;

/**
 * Release a database handle obtained from [`db_handle`]. Null-tolerant.
 *
 * # Safety
 *
 * `db` must be null or a pointer returned by [`db_handle`] that has not been closed yet.
 */
void rti_db_close(struct RtiDb *db);

/**
 * S1 reflex path: latest value for a series.
 *
 * Returns [`RTI_SAMPLE`] and writes `*out` when the series has a point, [`RTI_OK`]
 * when it is empty, or a negative error code. Steady-state: no heap allocation.
 *
 * # Safety
 *
 * `db` must be a live handle from [`db_handle`]; `out` must be valid for writing one
 * [`RtiSample`].
 */
int32_t rti_latest(const struct RtiDb *db, uint32_t series, struct RtiSample *out);

/**
 * S2 episodic context: open an ordered merging window over `series[0..series_len]`
 * for the half-open span `[start, end)`. Returns an opaque iterator handle, or null
 * on error (null arguments, `series_len == 0`, or `start >= end`).
 *
 * The handle must be released with [`rti_window_close`].
 *
 * # Safety
 *
 * `db` must be a live handle from [`db_handle`]; `series` must be valid for reading
 * `series_len` consecutive `u32` values.
 */
struct RtiWindow *rti_window_open(const struct RtiDb *db,
                                  const uint32_t *series,
                                  size_t series_len,
                                  int64_t start,
                                  int64_t end);

/**
 * Pull the next sample from a window: [`RTI_SAMPLE`] + `*out` written, [`RTI_OK`] at
 * end of stream, negative on error.
 *
 * # Safety
 *
 * `w` must be a live handle from [`rti_window_open`]; `out` must be valid for writing
 * one [`RtiSample`].
 */
int32_t rti_window_next(struct RtiWindow *w, struct RtiSample *out);

/**
 * Release a window handle obtained from [`rti_window_open`]. Null-tolerant.
 *
 * # Safety
 *
 * `w` must be null or a pointer returned by [`rti_window_open`] that has not been
 * closed yet.
 */
void rti_window_close(struct RtiWindow *w);

/**
 * Create a chunk buffer over `db` for `series` holding `chunk_len` action slots
 * aligned to a control period of `period_ns` nanoseconds. Returns null on error
 * (null db, `chunk_len == 0`). The handle must be released with [`rti_chunk_close`].
 *
 * # Safety
 *
 * `db` must be a live handle from [`db_handle`].
 */
struct RtiChunk *rti_chunk_new(const struct RtiDb *db,
                               uint32_t series,
                               uint32_t chunk_len,
                               uint64_t period_ns);

/**
 * Stage one action sample; never blocks. [`RTI_OK`] on success,
 * [`RTI_ERR_FULL`] when the chunk is full (seal it, then retry).
 *
 * # Safety
 *
 * `c` must be a live handle from [`rti_chunk_new`].
 */
int32_t rti_chunk_push(struct RtiChunk *c, struct RtiSample sample);

/**
 * Flush the staged chunk as one durable batch and return the durable watermark via
 * `*out_watermark`. [`RTI_OK`] on success, negative on error.
 *
 * # Safety
 *
 * `c` must be a live handle from [`rti_chunk_new`]; `out_watermark` must be valid for
 * writing one `u64`.
 */
int32_t rti_chunk_seal(struct RtiChunk *c, uint64_t *out_watermark);

/**
 * Release a chunk-buffer handle obtained from [`rti_chunk_new`]. Null-tolerant.
 * Staged-but-unsealed samples are dropped (they were never written to the db).
 *
 * # Safety
 *
 * `c` must be null or a pointer returned by [`rti_chunk_new`] that has not been
 * closed yet.
 */
void rti_chunk_close(struct RtiChunk *c);

#endif  /* RTI_VLA_H */
